### ISSUE TITLE
Speed up using `uv`

### ISSUE THREAD

**Issue by akaihola** [akaihola/repo-summary-post#5]
[uv](https://docs.astral.sh/uv/) is faster than [pip](https://pip.pypa.io/en/stable/).

The guide "[Using uv in GitHub Actions](https://docs.astral.sh/uv/guides/integration/github/)" recommends the official `setup-python` action in combination with `astral-sh/setup-uv@v2`:
```yaml
name: Example

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: "Set up Python"
        uses: actions/setup-python@v5
```

We could also enable [caching](https://docs.astral.sh/uv/guides/integration/github/#caching), but probably only based on an option in the `repo-summary-post` action.
